# This is a basic workflow to help you get started with Actions

name: Build & Deploy
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in paralle
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy a python app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}
          
          script: |
            cd alphawolfie
            git clone git@github.com:shininglegend/alphawolfie.git
            echo 'Deployment successful to Digital Ocean'
